import type { KeywordRecord } from "@/lib/types";

export const SEED_KEYWORDS: Omit<KeywordRecord, "id">[] = [
  {
    keyword: "chimney cleaning tucson",
    intent: "transactional",
    service: "chimney-cleaning",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Launch cluster primary",
    landingPage: "/az/tucson/chimney-cleaning",
  },
  {
    keyword: "chimney sweep tucson",
    intent: "transactional",
    service: "chimney-cleaning",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Strong commercial intent",
    landingPage: "/az/tucson/chimney-cleaning",
  },
  {
    keyword: "chimney repair tucson",
    intent: "commercial",
    service: "chimney-repair",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "High lead value",
    landingPage: "/az/tucson/chimney-repair",
  },
  {
    keyword: "emergency chimney service",
    intent: "transactional",
    service: "emergency-chimney-service",
    city: "",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Urgency cluster",
    landingPage: "/emergency-chimney-service",
  },
  {
    keyword: "how often to sweep chimney",
    intent: "informational",
    service: "chimney-cleaning",
    city: "",
    priority: "medium",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Guide with quote funnel",
    landingPage: "/how-often-to-sweep-chimney",
  },
  {
    keyword: "creosote dangers",
    intent: "informational",
    service: "chimney-cleaning",
    city: "",
    priority: "medium",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Safety guide cluster",
    landingPage: "/creosote-dangers",
  },
  {
    keyword: "chimney inspection tucson",
    intent: "commercial",
    service: "chimney-inspection",
    city: "tucson",
    priority: "medium",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Real estate + seasonal",
    landingPage: "/az/tucson/chimney-inspection",
  },
  {
    keyword: "chimney cap installation",
    intent: "commercial",
    service: "chimney-cap-installation",
    city: "",
    priority: "medium",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Monsoon damage angle",
    landingPage: "/chimney-cap-installation",
  },
];
